### ISSUE TITLE
HA custom component stops updating after 24 hours

### ISSUE THREAD

**Issue by GSzabados** [simontb/mojio-py#1]
Hi Simon,

I have a weird issue. The Mojio device tracker component what you have created  for HA stops updating after 24 hours. I use it as a custom component. I guess there is somewhere an issue regarding authentication or updating the access token. I haven't managed to debug it yet. 

Any advise how to debug the mojio-py and the device tracker component to see what is causing the issue?

Best Regards,

Gábor Szabados

**Comment by simontb** [comment]
Hi Gábor,

unfortunately I don't know how to debug the component, but I'm pretty sure I know the reason behind this behavior. The access token from Mojio is valid for 24 hours and has to be refreshed afterwards. I simply forgot to auto-renew the token. This should be fixed with 5cbe8c718389f5409502f0ad5d04450275fce795.

Kindly update the mojio-sdk of the home-assistant component to version 0.0.8 and let me know if this helps.

Best regards,
Simon

**Comment by martin131** [comment]
Just updated to 0.0.8.

**Comment by GSzabados** [comment]
Thanks @simontb. I thought the custom component did the refresh when it had an invalid token. But indeed, I haven't looked at the code of this module.

**Comment by GSzabados** [comment]
@simontb, it is working now as expected. I am closing now this issue. Thanks!
