### ISSUE TITLE
Moving the Mojio component to a separate repo to use as custom_component

### ISSUE THREAD

**Issue by GSzabados** [simontb/mojio-py#2]
Hi @simontb,

Would you mind to move the code from your HA PR to a separate repo to be able to use as a custom_component?

I can make a copy and make a repo by myself, but as you are the creator, I thought it would be better if you would have it as a repo. This way people could have it easier as a custom_component.

What do you think?

Best Regards,

Gábor

**Comment by simontb** [comment]
Great idea, @GSzabados 

Thanks again for your support. I'll create this repo, because I don't see myself addressing the requested changes to get it merged into the home assistant core repo.

Please give me a couple of days to do this. I'll get back to you once it's done. Should I forget it, feel free to remind me in ~2 weeks.

Best regards,
Simon

**Comment by simontb** [comment]
Hi @GSzabados,

I just created this repo: https://github.com/simontb/mojio-home-assistant

The code is simply in the folder `custom_components/mojio`. From how I understand it, this should suffice to use it (e.g. in HACS). However, I didn't test this, yet. If you encounter any issues, simply open an issue there.

I also didn't create any documentation, yet. If you'd like to contribute, feel free to open a PR.

Best regards,
Simon

**Comment by GSzabados** [comment]
Hi @simontb,

Thanks, I will definitely will do add some stuff there.

Best Regards,

Gábor
